name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: windows
    steps:
      - run: echo "[Info] Conectando ao ssh..."
      - run: ssh ubuntu@app.dev.smartenergia.com.br
      - run: cd /var/www/api
      - run: git pull origin dev
      - run: sudo php artisan config:clear
      - run: sudo php artisan cache:clear
      - run: sudo php artisan config:cache
      - run: sudo php artisan route:cache
      - run: sudo php artisan view:cache"
      - run: echo "[Info] Pull request enviado para o servidor de desenvolvimento."
      - run: echo "[Info] Repositório ${{ gitea.repository }} online para desenvolvimento."
      - run: echo "🍏 This job's status is ${{ job.status }}."